spring.application.name=RecipeNest

aws.region=eu-west-2
aws.s3.bucket=recipenest-images
aws.cloudfront.domain=${AWS_CLOUDFRONT_DOMAIN:}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
security.jwt.issuer=recipenest-api

# Frontend URL used to build email links
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
spring.profiles.active=dev

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000r