spring.application.name=RecipeNest
aws.region = eu-west-2
aws.s3.bucket = recipenest-images
aws.cloudfront.domain=d8hmvshmqgq8l.cloudfront.net
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled= true
spring.h2.console.path=/h2-console

jwt.secret = Ny+DxNo3tTipJY+0FMArl8uBl2sDlp95eooNSM8zff0=
jwt.expiration=86400000
security.jwt.issuer=recipenest-api

# Frontend URL used to build email links
app.frontend-url=http://localhost:3000
spring.profiles.active = dev

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=obiu7750@gmail.com
spring.mail.password=xsjcxohfnzyrlitg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true